 --------TABLA PAIS------------
ALTER TABLE PAIS ADD CONSTRAINT PK_PAIS PRIMARY KEY (cod_pais);
ALTER TABLE PAIS ADD CONSTRAINT ch_cod_pais CHECK (cod_pais IS NOT NULL);
ALTER TABLE PAIS ADD CONSTRAINT ch_nombre_pais CHECK (nombre_pais IS NOT NULL);

-------TABLA USUARIO------------
ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (cod_us);
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_PAIS FOREIGN KEY (cod_pais) REFERENCES PAIS(cod_pais);
ALTER TABLE USUARIO ADD CONSTRAINT ch_cod_us CHECK (cod_us IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT ch_nombre_us CHECK (nombre_us IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT ch_apellido_us CHECK (apellido_us IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT ch_sexo_us CHECK (sexo_us IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT ch_fechaNacimiento_us CHECK (fechaNacimiento_us IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT ch_correo_us CHECK (correo_us IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT ch_nomUsuario_us CHECK (nomUsuario_us IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT ch_password_us CHECK (password_us IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT ch_cod_pais_us CHECK (cod_pais IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT ch_numCelular_us CHECK (numCelular_us IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT ch_peso_us CHECK (peso_us IS NOT NULL);
ALTER TABLE USUARIO ADD CONSTRAINT ch_estatura_us CHECK (estatura_us IS NOT NULL);

--------TABLA RUTINA------------
ALTER TABLE RUTINA ADD CONSTRAINT PK_RUTINA PRIMARY KEY(cod_rut);
ALTER TABLE RUTINA ADD CONSTRAINT FK_RUTINA_USUARIO FOREIGN KEY (cod_us) REFERENCES USUARIO(cod_us);
ALTER TABLE RUTINA ADD CONSTRAINT ch_cod_rut CHECK (cod_rut IS NOT NULL);
ALTER TABLE RUTINA ADD CONSTRAINT ch_cod_us_rut CHECK (cod_us IS NOT NULL);
ALTER TABLE RUTINA ADD CONSTRAINT ch_nombre_rut CHECK (nombre_rut IS NOT NULL);
ALTER TABLE RUTINA ADD CONSTRAINT ch_cuerpo_corporal_rut CHECK (cuerpo_corporal_rut IS NOT NULL);
ALTER TABLE RUTINA ADD CONSTRAINT ch_numSeries_rut CHECK (numSeries_rut IS NOT NULL);
ALTER TABLE RUTINA ADD CONSTRAINT ch_numRepeticiones_rut CHECK (numRepeticiones_rut IS NOT NULL);
ALTER TABLE RUTINA ADD CONSTRAINT ch_tiempoRepeticiones_rut CHECK (tiempoRepeticiones_rut IS NOT NULL);
ALTER TABLE RUTINA ADD CONSTRAINT ch_nom_time1_rut CHECK (nom_time1_rut IS NOT NULL);