 ----------DROP SEQUENCE--------------------
 DROP SEQUENCE RUTINA_SEQ;
 DROP SEQUENCE USUARIO_SEQ;
 
---------SEQUENCE USUARIO_SEQ--------------------
CREATE SEQUENCE USUARIO_SEQ 
START WITH 200
INCREMENT BY 1
NOCACHE;

---------SEQUENCE RUTINA_SEQ--------------------
CREATE SEQUENCE RUTINA_SEQ 
START WITH 400
INCREMENT BY 1
NOCACHE;