--------TRUGGER DE TABLA USUARIO------------
CREATE OR REPLACE TRIGGER INC_USUARIO
BEFORE INSERT ON USUARIO 
REFERENCING NEW AS NEW OLD AS OLD 
FOR EACH ROW

BEGIN
  SELECT USUARIO_SEQ.NEXTVAL
  INTO   :new.cod_us
  FROM   dual;
END INC_USUARIO;
/

 --------TRUGGER DE TABLA RUTINA------------
CREATE OR REPLACE TRIGGER INC_RUTINA
BEFORE INSERT ON RUTINA 
REFERENCING NEW AS NEW OLD AS OLD 
FOR EACH ROW

BEGIN
  SELECT RUTINA_SEQ.NEXTVAL
  INTO   :new.cod_rut
  FROM   dual;
END INC_RUTINA;
/